# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='comments',
            field=models.TextField(blank=True, default='N/A'),
        ),
        migrations.AlterField(
            model_name='review',
            name='comments',
            field=models.TextField(blank=True, default='N/A'),
        ),
    ]
