# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_auto_20160620_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='school',
            field=models.CharField(default='school', max_length=100),
        ),
    ]
