# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 03:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_auto_20160621_2226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='listing_addr',
            new_name='address',
        ),
    ]
