# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 03:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_auto_20160621_2228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='published_date',
        ),
        migrations.RemoveField(
            model_name='review',
            name='published_date',
        ),
    ]
